version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql-storedb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: storedb
      MYSQL_USER: storeuser
      MYSQL_PASSWORD: storepassword
    ports:
      - "3306:3306"